//all of the songdata is here
//should be loaded first
//they have keys even though its not that useful (yet?) cause i was
//reusing old formatter code from a failed vocaloid songDB attempt
//and when i realised it wasnt useful i was too lazy to redo lol

//songs split by producer
songdata = {
    // "Collabs":{
    //     //sakura tattoo, frankenX, unmei, fucking hell i have to add the entire chimera collection
    // },
    "DECO*27":{
        "JOU9258":['Journey', 'DECO*27', 'Hatsune Miku', 'BTekXS9d-no'],
        "ZOM2283":['Zombies', 'DECO*27', 'Hatsune Miku', 'NkBq2bYuvJI'],
        "LOV3118":['Love Words IV', 'DECO*27', 'Hatsune Miku', 'aHNWL7MBXoc'],
        "CHI9413":['Chimera', 'DECO*27', 'Hatsune Miku', 'c6HKcNVbByc'],
        //MANNEQUINN
        "STA3399":['Status Effect: Girlfriend', 'DECO*27', 'Hatsune Miku', 'n4eJ5mrpaQM'],
        "U0040":['U', 'DECO*27', 'Hatsune Miku', 'YYaOZ5_VnWc'],
        "DIL0439":['Dilemma', 'DECO*27', 'Hatsune Miku', 'E_PfhNftyh4'],
        "PAR3834":['Parasite', 'DECO*27', 'Hatsune Miku', 'agcoHM2CJ3s'],
        "SAL7706":['Salamander', 'DECO*27', 'Hatsune Miku', '-H2PCK7DJsQ'],
        "ANI9586":['Animal', 'DECO*27', 'Hatsune Miku', 'HtBqK6xsQ9k'],
        "MOZ8213":['Mozaik Role (Reloaded)', 'DECO*27', 'Hatsune Miku', 'WysuxO4yR04'],
        "RHY3293":['Rhythm', 'DECO*27', 'Hatsune Miku', 'pyTeUQpAOwY'],
        "CIN5698":['Cinderella', 'DECO*27', 'Hatsune Miku', 'adGhT_-JbZI'],
        "STI5831":['Stickybug II', 'DECO*27', 'Hatsune Miku', 'EJMf1NdrYjo'],
        //UNDEAD ALICE
        "ADD6606":['Addiction', 'DECO*27', 'Hatsune Miku', 'cJjqth04G1Q'],
        "NEO4720":['Neo-Neon', 'DECO*27', 'Hatsune Miku', 'D7HH-3wkCJc'],
        "UND7171":['Undead Alice', 'DECO*27', 'Hatsune Miku', '3CsQyaZOHhI'],
        "PSE6228":['Pseudo-Hope Syndrome', 'DECO*27', 'Hatsune Miku', 'KgczJh0uX5o'],
        "NEE1403":['needLe', 'DECO*27', 'Hatsune Miku', 'buoYwfZG4vQ'],
        "TWO8927":['Two Breaths Walking (Reloaded)', 'DECO*27', 'Hatsune Miku', 'iM8d0SzJTIU'],
        "POS6202":['Positive Parade', 'DECO*27', 'Hatsune Miku', 'zSfMHbogn00'],
        "FAK1726":['Fake Actor', 'DECO*27', 'Hatsune Miku', 'qAd259QwSJs'],
        "SEC5673":['Secret Feast', 'DECO*27', 'Hatsune Miku', 'INCiFuU1T10'],
        "THE2076":['Theory of Negativity', 'DECO*27', 'Hatsune Miku', 'UrqEy_arieg'],
        //ANDROID GIRL
        "AND1778":['Android Girl', 'DECO*27', 'Hatsune Miku', 'uFRPeiAEO0M'],
        "REL7244":['Relationship Scramble', 'DECO*27', 'Hatsune Miku', 'nj82E1_70sQ'],
        "MOS9973":['Mosquito', 'DECO*27', 'Hatsune Miku', 'W95-akBGsVk'],
        "OTO0878":['Otome Dissection', 'DECO*27', 'Hatsune Miku', '7zwCIz-Ohn4'],
        "WE 8669":['We The Hostages', 'DECO*27', 'Hatsune Miku', 'd_svmw65Mgk'],
        "PSY5694":['Psychogram', 'DECO*27', 'Hatsune Miku', 'VE4wegMHIMk'],
        "NOC7156":['Nocturnal Kids', 'DECO*27', 'Hatsune Miku', 'WXl1ZPk--Zs'],
        "HIB4577":['Hibana', 'DECO*27', 'Hatsune Miku', 'hxSg2Ioz3LM'],
        "LOV8716":['Love Words III', 'DECO*27', 'Hatsune Miku', 'WptXk39wiIQ'],
        //GHOST
        "FIR3207":['First Storm', 'DECO*27', 'Hatsune Miku', 'L7BxD7HHWl4'],
        "GHO9605":['Ghost Rule', 'DECO*27', 'Hatsune Miku', 'KushW6zvazM'],
        "REV9106":['Reversible Campaign', 'DECO*27', 'Hatsune Miku', 'RqxnjgFj1HU'],
        "MKD5025":['MKDR', 'DECO*27', 'Hatsune Miku', 'fYflKwU365Q'],
        "1188693":['118', 'DECO*27', 'Hatsune Miku', 'Q6KJG0k6ALs'],
        "TUR7305":['Turret of Justice', 'DECO*27', 'Hatsune Miku', 't4czZ4T_cTc'],
        "LIA7453":['Liar Dance', 'DECO*27', 'Hatsune Miku', 'FOvfM0fe-FE'],
        "FIN9602":['Find The Light', 'DECO*27', 'Hatsune Miku', 'G5b9MwHTliI'],
        "HED9661":['Hedgehog', 'DECO*27', 'Hatsune Miku', 'LLvlVE_iuZg'],
        "AT9920":['at', 'DECO*27', 'Hatsune Miku', 'WemvMO-2DRc'],
        "SWO2739":['Swordfigthing Johnny', 'DECO*27', 'Hatsune Miku', '9qVm_1fGF6I'],
        //conti new
        "ROO6471":["Rooter's Song", 'DECO*27', 'Hatsune Miku', '7DCgArsBq4s'],
        "HEA2191":['Heart A La Mode', 'DECO*27', 'Hatsune Miku', 'LE1XskraNfI'],
        "LOV4528":['Love Doll', 'DECO*27', 'GUMI', 'Ak9S5ibCuyk'],
        "STR7586":['Streaming Heart', 'DECO*27', 'Hatsune Miku', '9DD6JvY06Ok'],
        "STI4470":['Stickybug', 'DECO*27', 'Hatsune Miku', 'wv2P0PLz9fw'],
        "MON9618":['Mono Poisoner', 'DECO*27', 'Hatsune Miku', '3bEikMqDd3M'],
        "LON4561":['Lonely Shit', 'DECO*27', 'Hatsune Miku, Hatsune Miku', 'v6PEfaXUY3g'],
        "STA2127":['Starlight Girl', 'DECO*27', 'Hatsune Miku', 'rA1iBNbD764'],
        "BUM4727":['Bump Babe', 'DECO*27', 'Hatsune Miku', '2lZlUB5VvO4'],
        "WIN2614":['Winter Cleaning', 'DECO*27', 'Hatsune Miku', 'HJIFqUxi4ko'],
        "FAK3656":['Fakery Tale', 'DECO*27', 'Hatsune Miku', 'fEcTEk9eQtc'],
        "ANT0660":['Anti Beat', 'DECO*27', 'Hatsune Miku', 'Odjy0CHW9XI'],
        "DEL9471":['Delusion Tax', 'DECO*27', 'Hatsune Miku', 'sWvZfwY8beg'],
        "AUG4119":['August 31st', 'DECO*27', 'Hatsune Miku', 'WlXW5O-YX7w'],
        "AIM7959":['Aimai Elegy', 'DECO*27', 'Hatsune Miku', 'SBKFxcyfdug'],
        "AN4711":['an', 'DECO*27', 'Hatsune Miku', 'bVpSJGqfX0I'],
        //icant keep track anymore. pre2012 deco
        "YUM9850":['Yumeyume', 'DECO*27', 'Hatsune Miku', '07r67gGbtLQ'],
        "TWO2225":['Two Breaths Walking', 'DECO*27', 'Hatsune Miku', 'cFbWl2aPdTk'],
        "MOZ7490":['Mozaik Role', 'DECO*27', 'GUMI', 'DnLFVUi3oOU'],
        "COW3382":['Coward Montblanc', 'DECO*27', 'GUMI', 'B-A2eYlbrwQ'],
        "CRI9071":['Crime and Punishment', 'DECO*27', 'Hatsune Miku', '3xAzQ8-WXMQ'],
        "HEA1445":['Heartbreak Summit', 'DECO*27', 'Hatsune Miku', 'QssHc_SqCZc'],
        "ONC3434":['Once Upon a Me', 'DECO*27', 'Hatsune Miku', 'HK_Ct9t1U6s'],
        "AIK2341":["Ai Kotoba", "DECO*27", "Hatsune Miku", "I0eeS5wYGzI"],
    },
    "PinocchioP":{
        //no album yet
        "KIL2345":['Killer Spider', 'PinocchioP', 'Hatsune Miku', '-F_iX-La024'],
        "2302695":['2:30 Life Remaining', 'PinocchioP', 'Hatsune Miku', '8yUDr7BQYEo'],
        "REI8310":['Reincarnation Apple', 'PinocchioP', 'Hatsune Miku', 'LYWP8HtgeLQ'],
        "MAG7941":['Magical Girl and Chocolate', 'PinocchioP', 'Hatsune Miku', 'T2kS1gAbxhc'],
        "GOD6923":['God-ish', 'PinocchioP', 'Hatsune Miku', 'EHBFKhLUVig'],
        //love (2021)
        "LOV8555":['Loveit', 'PinocchioP', 'Hatsune Miku', '--41OGPMurU'],
        "ULT0856":['Ultimate Senpai', 'PinocchioP', 'Hatsune Miku', 'MnJq5kSn-GY'],
        "NEE2697":['Nee Nee Nee.', 'PinocchioP', 'Hatsune Miku, Kagamine Rin', 'w8yweCungCE'],
        "SEC2623":['Secret HIMITSU', 'PinocchioP', 'Hatsune Miku', 'UZXPxdJqPBA'],
        "LOV1588":['Love for Love by Love of Love', 'PinocchioP', 'Hatsune Miku', 'QvO8kcWFFT0'],    
        "KIC0768":['KICK-ASS *LITERALLY', 'PinocchioP', 'Hatsune Miku', 'f4hb4Fyyylc'],
        "ANT5926":['Antenna', 'PinocchioP', 'Hatsune Miku', 'bwMGqyTmoro'],
        "4041957":['404', 'PinocchioP', 'Hatsune Miku', 'yduFuBC4whg'],
        "DON5493":["Don't be fooled by weird love", 'PinocchioP', 'Hatsune Miku', 'YVxQLAHdRGo'],    
        "NON7316":['Non-breath oblige', 'PinocchioP', 'Hatsune Miku', 'lw7pcm1W5tw'],
        "LOV6646":['LOVE', 'PinocchioP', 'Hatsune Miku', '7gZXfS6DB5k'],
        "THE2282":["The World Hasn't Even Started Yet", 'PinocchioP', 'Hatsune Miku', '1s8NNPgdl5g'],
        "BEC2317":["Because You're Here", 'PinocchioP', 'Hatsune Miku', 'ygY2qObZv24'],
        "ONI2966":['Onion+', 'PinocchioP', 'Hatsune Miku', '7rUakfZ1jCo'],
        "IJU8388":['I Just Hate People+', 'PinocchioP', 'Hatsune Miku', 'cm2Xz8WKf-4'],
        //zerogo 2019
        "NOB0963":['Nobody Makes Sense', 'PinocchioP', 'Hatsune Miku', 'LtSNzPyo0lA'],
        "GHO2813":['Ghosts Play to the Audience', 'PinocchioP', 'Hatsune Miku', 'M92c6pl10u0'],   
        "YOZ9390":['Yozurina', 'PinocchioP', 'Hatsune Miku', 'qrm-kGEA6jA,'],
        "WHA9337":['Whatever Yama Says Goes', 'PinocchioP', 'Hatsune Miku', 'Tg5z_8286ms'],       
        "MEI9178":['Mei Mei', 'PinocchioP', 'Hatsune Miku', 'MKrVBS6pX9I,'],
        "SIC9347":['Sick Sick Sick', 'PinocchioP', 'Hatsune Miku', 'gNKgqg3FISw'],
        "BEA5741":['Beautiful Fiction', 'PinocchioP', 'Hatsune Miku', '9kRa_S1G4Ok'],
        "WHA4406":["What's Inside", 'PinocchioP', 'Hatsune Miku', 'GSpwTvYgFrM'],
        "ZER0862":['Zero', 'PinocchioP', 'Hatsune Miku', 'xy58QqB4NJA'],
        "THA9946":['Thanks For Being Lifeless', 'PinocchioP', 'Hatsune Miku', 'Aa3rgnV6WY8'],     
        //Zoushoku Suru Imamura 2017
        "VOC5202":['Vocaloids are Lame', 'PinocchioP', 'Hatsune Miku', 'bFZoeJn3G3o'],
        "THE9815":["There's Nothing", 'PinocchioP', 'Hatsune Miku', 'vzP1scr5l2w'],
        "APP4407":['Apple dot com', 'PinocchioP', 'Hatsune Miku', 'h1pSSrmdEtw'],
        "IT'3507":["Besides, it's always the others who die", 'PinocchioP', 'Hatsune Miku', 'Qajk9EJ3LfY'],
        //comic and cosmic 2016
        "FLO4899":['Floating Shelter', 'PinocchioP', 'Hatsune Miku', 'ODfip8xt1Aw'],
        "AT 4864":['At The Mercy of Emptiness', 'PinocchioP', 'Hatsune Miku', 'uAb7d7V7GMw'],   
        "DRE3779":['Dream Cat', 'PinocchioP', 'Hatsune Miku', 'G9oWKfLap-g'],
        "OZ0426":['Oz', 'PinocchioP', 'Hatsune Miku', '5P92PqI4UxM'],
        "ROT0733":['Rotten Heresy and Chocolate', 'PinocchioP', 'Hatsune Miku', 'sHnvEsNU1X0'], 
        "MUT7762":['Mutant in Love', 'PinocchioP', 'Hatsune Miku', '4Yl4DO1F5CY'],
        "HAP5941":['Happy Very Happy', 'PinocchioP', 'Hatsune Miku', 'RQP3M2dlmIc'],
        "VAG3491":['Vague', 'PinocchioP', 'Hatsune Miku', 'DBTjK5y68jA'],
        "GOO3910":['Goodbye, Mr. Spirit', 'PinocchioP', 'Hatsune Miku', 'PC4P9Iy3WgM'],
        "'CA5881":["'Cause I'm A Dreg Too", 'PinocchioP', 'Hatsune Miku', 'wYOGcPSNTeU'],       
        "NIN8982":['Nina', 'PinocchioP', 'Hatsune Miku', '9bRVnm6pUD8'],
        "WEE9100":['Weekly Shounen Bye Bye', 'PinocchioP', 'Hatsune Miku', 'Wbmaphf-kJ8'],      
        "M/E7671":['m/es', 'PinocchioP', 'Hatsune Miku', 'mIyFIenBlzg'],
        "BLE4378":['Bleah!', 'PinocchioP', 'MAYU', 'FHzriFn_nPU'],
        "WHA8314":['What Children Are Made Of ', 'PinocchioP', 'Hatsune Miku', 'e_a7FGe_hxY'],  
        "STR7236":['Strange Animal', 'PinocchioP', 'Hatsune Miku, Kagamine Rin', '9QjSNh8bY-w'],
        "FRO6709":["Frog's Song", 'PinocchioP', 'Kagamine Rin', '4guNd9X73BA'],
        "PLA9882":['Planet Masshirake', 'PinocchioP', 'Hatsune Miku', 'eVDITkiYUy8'],
        "LON7143":['Lonely UFO', 'PinocchioP', 'Hatsune Miku', 'WOJlJd0nAMI'],
        "GAM2688":['Game Specter 2', 'PinocchioP', 'Hatsune Miku', 'OfXUHMYccu4'],
        "SCH8561":['Scheveningen', 'PinocchioP', 'Hatsune Miku', 'KXr5X2s8lAc'],
        //gave up counthing here :thumbsup
        "EVE5064":['Everything About Animals', 'PinocchioP', 'Hatsune Miku', 'Oyc1zJ4L6UA'],
        "FEA1255":['Feast of Absurdity', 'PinocchioP', 'Hatsune Miku', 'D6dwEFGL_KI'],
        "IT窶8818":["It's Matsuri, Hey Come On!", 'PinocchioP', 'Hatsune Miku', 'FDd3m_Tr0m0'],
        //add , above
        "CRA0666":['Crappy Fantasy Days', 'PinocchioP', 'Hatsune Miku', 'p_FAIIuBXl8'],
        "I'M0982":["I'm glad you're evil too", 'PinocchioP', 'Hatsune Miku', 'PLevj9bdRRA'],
        "ALL3198":['All I Need are Things I Like', 'PinocchioP', 'Hatsune Miku', 'mYHJPb9PuUM'],
        "1YE7880":['1year', 'PinocchioP', 'Hatsune Miku', 'FdRljyIlgEo'],
        "POL9432":['Polygon Teacher', 'PinocchioP', 'Hatsune Miku', 'MD_wy07HB50'],
        "I. 5935":['i. c. u', 'PinocchioP', 'Hatsune Miku', 'di3dz0luD1I'],
        "MOT7968":['Motivation is Dead', 'PinocchioP', 'Hatsune Miku', 'lCBF_XSFmng'],
        //Antenna?
        "TOK3480":['Tokyo Mannequin', 'PinocchioP', 'Hatsune Miku', 'krdYAGZOkho'],
        "NIC0262":['Nice To Meet You, Mr Earthling', 'PinocchioP', 'Hatsune Miku', 'e1gY8dUfKxg'],
        //replace ,
        "BLA1994":['Black Hole Ville Shopping Street', 'PinocchioP', 'Hatsune Miku', 'fcU4wX9szSk'],
        "MED6629":['Medicine for Good Kids', 'PinocchioP', 'Hatsune Miku', '2xHeS9up5rE'],
        "OBL2073":['Oblivious Pumpkin', 'PinocchioP', 'Hatsune Miku', 'A8hnlbtMsUs'],
        "LOV9151":['Love is Onomatopoeia', 'PinocchioP', 'Hatsune Miku', 'fFZqDmGvlRw'],
        "SLO0361":['SLoWMoTIoN', 'PinocchioP', 'Hatsune Miku', 'ARt2fVT33Lw'],
        "MY 2144":['My Friend Who Was Good At Drawing', 'PinocchioP', 'Hatsune Miku', '0tluBqFbAgQ'],
        "LAS7655":['Last Continue', 'PinocchioP', 'Hatsune Miku', 'ZxLLYhL6pEc'],
        "GOR8459":['Gorgeous Big Conversation', 'PinocchioP', 'Hatsune Miku', 'b6_Buws3bpw'],
        //obscure questions 2012
        "JIZ9087":['Jizemi In The Underground', 'PinocchioP', 'Hatsune Miku', 'lf_Nn7noK_w'],
        "EAC0941":['Each of Us Has Our Own Life', 'PinocchioP', 'Hatsune Miku', '-t3gg6NH_kA'],
        "COM2462":['Common World Domination', 'PinocchioP', 'Hatsune Miku', '8Z3TbMBfDM0'],
        "WON3338":['Wonderous Little Boxes', 'PinocchioP', 'Hatsune Miku', 'NyzFgvKnoqw'],
        "DON7257":["Don't Kill The Love Song", 'PinocchioP', 'Hatsune Miku', 'S1w2UR1OVJE'],
        "RAR2804":['RARENO', 'PinocchioP', 'Hatsune Miku', 'UxztmiFz268'],
        "MON0230":['Monster Universe', 'PinocchioP', 'Hatsune Miku', 'A3oQOEUeQk4'],
        "MEM8910":['Memury Shabadaba', 'PinocchioP', 'Hatsune Miku', 'ypTGLYmU0zQ'],
        "MUS0695":['Mushroom Mother', 'PinocchioP', 'Hatsune Miku', 'pyzgN2DL4fY'],
        "THE4301":['The Vocaloid Songs 10 Years Later', 'PinocchioP', 'Hatsune Miku', 'hmd1_P5kvDg'],
        "PSY1661":['Psychedelic Smile', 'PinocchioP', 'Hatsune Miku', 'zKKkzsGAa4M'],
        "THE3777":['The Scraped Angel', 'PinocchioP', 'Hatsune Miku', 'okLzn2tuwG0'],
        "EIG1815":['eight hundred', 'PinocchioP', 'Hatsune Miku', '2trNXrUuGrs'],
        "FIR5139":['Fireworks', 'PinocchioP', 'Hatsune Miku', 'hd9Ilaw_m4U'],
        "MY 4647":['My Way Home Alone', 'PinocchioP', 'Hatsune Miku', 'aq1HpndmJgo']
    },
    "wowaka":{
        "UNK2497":['Unknown Mother Goose', 'wowaka', 'Hatsune Miku', 'P_CSdxSGfaA'],
        "UNH5240":['Unhappy Refrain', 'wowaka', 'Hatsune Miku', 'uMlv9VWAxko'],
        "NIC4061":['Nichijou to Chikyuu no Gakubuchi', 'wowaka', 'Hatsune Miku', 'sbZeGMATFL4'],
        "HIM8174":['Himitsu no Nedan', 'wowaka', 'Hatsune Miku', 'Ams_PbDs4qk]'],
        "ISH4623":['Ishiki no Nedan', 'wowaka', 'GUMI', 'jl8sPBzRi0Y'],
        "REV7776":['Reversible Doll', 'wowaka', 'Hatsune Miku', 'hUZDe8LEnEgW'],
        "TEN5965":['Tenbin, Tokei, Denwa', 'wowaka', 'Hatsune Miku', '3lCs_-GQ2As'],
        "WOR3920":["World's End Dancehall", 'wowaka', 'Hatsune Miku, Megurine Luka', 'ZB75e7vzX0I'],
        "ROL7381":['Rolling Girl', 'wowaka', 'Hatsune Miku', 'vnw8zURAxkU'],
        "TSU1518":['Tsumiki no Ningyou', 'wowaka', 'Hatsune Miku', '6nrK6iTVkz4'],
        "ZUR6998":['Zurete Iku', 'wowaka', 'Hatsune Miku', 'e5JjR7XVtEo'],
        "TWO2325":['Two-Sided Lovers', 'wowaka', 'Hatsune Miku', 'b_cuMcDWwsI'],
        "BOK4646":['Boku no Sainou', 'wowaka', 'Hatsune Miku', '0aDhPfeNtwg'],
        "TOO6095":['Toosenbo', 'wowaka', 'Hatsune Miku', 'uxNoOPetZ6g'],
        "LIN5166":['Line Art', 'wowaka', 'Hatsune Miku', 'DXcY0HUURKw'],
        "TEN3904":['Tenohira', 'wowaka', 'Hatsune Miku', 'sVRGyUnOWtY'],
        "GRE8160":['Grey Zone nite.', 'wowaka', 'Hatsune Miku', 'hkKoaWTjVds'],
    },
    "Iyowa":{
        //no album yet
        "HEA0060":['Heat abnormal', 'Iyowa', 'Adachi Rei', 'b2NTglk9tvI'],
        "PRI4138":['PRIMARY', 'Iyowa', 'KAFU', 'pIF_snWKz2g'],
        "TAK2466":['Take you to an alien', 'Iyowa', 'SEKAI', 'PubukElqUJw'],
        "AKU1245":['AKUMA!', "Iyowa", "SOLARIA", "0785eNaV48s"],
        "PIN4387":['Pinedrop', 'Iyowa', 'Hatsune Miku', 'y1K8OBOU5kM'],
        "WAR2442":['Warera wa Hare', 'Iyowa', 'Hatsune Miku', '4TfxYl94XQ4'],
        //watashi no heritage (2021)
        "OVE2334":['OVER!', 'Iyowa', 'Hatsune Miku, Kaai Yuki', '_ZKSftirY3A'],
        "GOL9629":['Golden Number', 'Iyowa', 'Hatsune Miku, flower', '_YpcTBm15QU'],
        "CLO7408":['CLover Knight', 'Iyowa', 'Hatsune Miku, flower, Kaai Yuki, GUMI', 'iFo-ie2lJvg'],
        "APR3420":['apricot', 'Iyowa', 'Hatsune Miku', '_uMDEIPgmFI'],
        "ALM2237":['Almost Ended', 'Iyowa', 'Hatsune Miku, flower', 'GiDo4s1x9Mw'],
        "ADI4675":['Adipocere', 'Iyowa', 'Hatsune Miku', 'Wr-2xcQkke4'],
        "URA9125":['Urapocere', 'Iyowa', 'Hatsune Miku', '0Pof0we5jVA'],
        "KYU9984":['Kyuukurarin', 'Iyowa', 'KAFU', '2b1IexhKPz4'],
        "HEA9071":["Heaven's Bug", 'Iyowa', 'Hatsune Miku, Kaai Yuki', 'v5BloiCJCys'],
        "POT1815":['Potpourri-san', 'Iyowa', 'Hatsune Miku, flower', 'I1kPD4gHMaw'],
        "GOO7708":['Goodbye Jackpot', 'Iyowa', 'Hatsune Miku, flower', 'xym6yLUncNY'],
        "LIV7996":['living millennium', 'Iyowa', 'Hatsune Miku', '3em-J9yYPAo'],
        //nemuru pink noise (2019)
        "I A0161":['I am taboo', 'Iyowa', 'Hatsune Miku, flower', 'al263xnknLE'],
        "IMA3655":['IMAWANOKIWA', 'Iyowa', 'Hatsune Miku', 'OVwCr2MESfo'],
        "GRA0885":['Gradual Suppuration', 'Iyowa', 'Hatsune Miku, flower', 'sSXfjIxeJDs'],
        "DEA2978":['Dear My Witchcraft', 'Iyowa', 'Hatsune Miku, flower', 'NDKwiNTPhEw'],
        "YOU0323":['You are Innocent Monster', 'Iyowa', 'Hatsune Miku, flower', 'HPPp1cb5rcc'],
        "MER2411":['Mercy Killing', 'Iyowa', 'Hatsune Miku, flower', 'BJoL1U52ebc'],
        "DON4980":["Don't Return to the Water Corpse", 'Iyowa', 'Hatsune Miku, flower', '1bTQMYnEf_Y'],
        "LAS0884":['Last Journey', 'Iyowa', 'Hatsune Miku, flower', 'y6JY8ZPufb0'],
        "ANG8015":['Angel Care', 'Iyowa', 'Hatsune Miku, flower', 'eBQHmbJ1ur0']
    },
    "Niru Kajitsu":{
        "HEA9468":['Heaven Dope', 'Niru Kajitsu', 'flower', '9tM2PHAjgss'],
        "TRI1268":['Tricologe', 'Niru Kajitsu', 'flower', 'umOuwAIizAQ'],
        "BAB4742":['Baba Yaga', 'Niru Kajitsu', 'flower', 'aOelHbwkRD4'],
        "ANT4701":['Antidote', 'Niru Kajitsu', 'flower', 'E0RgPLkB5lg'],
        "ARA9695":['Arandano', 'Niru Kajitsu', 'flower', 'E3xVcw7--aM'],
        "IRO8702":['Ironina', 'Niru Kajitsu', 'flower', 'LiYS214Qh5A'],
        "SAL6536":['Salvador', 'Niru Kajitsu', 'flower', 'jszjF6mYfYc'],
        "DOC7348":['Doctorine', 'Niru Kajitsu', 'flower', 'RawnaIb9Pvc'],
        "NIG1972":['Night Rule', 'Niru Kajitsu', 'KAFU', 'MLE6Fvg7ci0'],
        "DIZ0297":['DiZzy Dizzy', 'Niru Kajitsu', 'flower', '5iymwRXrkZA'],
        "STR8102":['Strelitzia', 'Niru Kajitsu', 'flower', 'GfWbg86LhXs'],
        "YES3510":['Yesman', 'Niru Kajitsu', 'flower', 'iZ6lpTC16_Q'],
        "BRI6064":['Bride and Groom ga Tooru', 'Niru Kajitsu', 'Hatsune Miku', 'wE-grtXUZXc'],
        "GU-4319":['Gu-Gu', 'Niru Kajitsu', 'IA', '9cxL0j5dXRU'],
        "WOR4856":['Workaholic', 'Niru Kajitsu', 'flower', '7GsNcms843k'],
        "RIN4557":['Rinshokuka', 'Niru Kajitsu', 'flower', 'tOI2RHCxKno'],
        "HIG8679":['High-Low Agate', 'Niru Kajitsu', 'flower', 'Ja7NntmU2s8'],
        "HAI0690":['Haine & Kleine', 'Niru Kajitsu', 'flower', 'V4qmCkT2i_o'],
        "ANN2621":['ANNA NO MUSICA', 'Niru Kajitsu', 'flower', 'PK2CS8vK3BA'],
        "TRA4880":['Traffic Jam', 'Niru Kajitsu', 'flower', 'oUevY6uH4Qg'],
        "LIF9666":['LIFE BAUTE', 'Niru Kajitsu', 'flower', 'M8OH36F1Vj8'],
        "WOZ7970":['Wozwald', 'Niru Kajitsu', 'flower', 'mVjyVppveGY'],
        "NEI0568":['Neira', 'Niru Kajitsu', 'Hatsune Miku', 'SAJCzFqHFEs'],
        "SHA3758":['Shama', 'Niru Kajitsu', 'flower', 'tQWMArNo9F0'],
        "AI 0837":['Ai Aru Kanchigai', 'Niru Kajitsu', 'flower', 'sAHYQ8TrCWQ'],
        "SUR1950":['Surreal Man', 'Niru Kajitsu', 'IA', 'xTD_CODiTqM'],
        "HUN4301":['Hungry Nicole', 'Niru Kajitsu', 'flower', 'N4MEB95GRe0'],
        "MUD4183":['Muddy Marmalade', 'Niru Kajitsu', 'flower', 'pqwtbSyFsHs'],
        "BEC9448":['Because Andrew said', 'Niru Kajitsu', 'flower', 'jfJHFh7uyNA']
    },
    "NayutalieN":{
        "SEC3199":['Secret UFO', 'NayutalieN', 'KAFU', 'h-HMdNsCFus'],
        "MIZ7672":['Mizuiro Shinryaku', 'NayutalieN', 'Hatsune Miku', 'Mksf3xakH8s'],
        "MOR0009":['More! Jump! More!', 'NayutalieN', 'Hatsune Miku + MORE MORE JUMP', 'SKbutknpQ_I'],
        //Nayutan Sei Kara no Buttai N  (2022)
        "BEA0147":['Beats of Jupiter', 'NayutalieN', 'Hatsune Miku', '5FiTUHo9G48'],
        //Nayutan Sei Kara no Buttai z (2018)
        "COM2562":['Comet Honeymoon', 'NayutalieN', 'Hatsune Miku', 'wCj04kwAFX8'],
        "DAN2650":['Dance of Venus', 'NayutalieN', 'Hatsune Miku', 'fd8uXlrr5is'],
        "REV7537":['Reverse Universe', 'NayutalieN', 'Hatsune Miku', 'VyRrUt_lTGo'],
        //Nayutan Sei Kara no Buttai Y (2016)
        "ALI7298":['Alien Alien', 'NayutalieN', 'Hatsune Miku', '2t1NMRse6aI'],
        "DAN0845":['Dance Robot Dance', 'NayutalieN', 'Hatsune Miku', 'g7dvpD_zlIM'],
        "SOL3523":['Solar System Disco', 'NayutalieN', 'Hatsune Miku', 'Ja9qmYjXk6U'],
        "PLA0099":['Planet Loop', 'NayutalieN', 'Hatsune Miku', 'LNX0GsjBP2w'],
        //Nayutan Sei Kara no Buttai X (2016)
        "AND8982":['Andromeda Andromeda', 'NayutalieN', 'Hatsune Miku', 'ziubPl820DA'],
        "FLI5582":['Flight Girl', 'NayutalieN', 'Hatsune Miku', 'JGRgYC1p8qk'],
        "PER1455":['Perfect Life', 'NayutalieN', 'Hatsune Miku', 'ou-ZYF0WO20'],
        "HOW4977":['How To Warp', 'NayutalieN', 'Hatsune Miku', 'vQSFmQBtlRY'],
        "ATO8078":['Atomic Love', 'NayutalieN', 'Hatsune Miku', 'JIdF-QzPJTw'],
        "ROC4715":['Rocket Cider', 'NayutalieN', 'Hatsune Miku', '3x9_LpnRtAk'],
        "STR0048":['Strato Stella', 'NayutalieN', 'Hatsune Miku', 'nyOrgo8JkyA']
    }
}

